### ISSUE TITLE
Criar variáveis de ambiente

### ISSUE THREAD

**Issue by paulogesualdo** [magdieline/encurtador-de-url#7]
Segue link para auxiliar: https://www.freecodecamp.org/portuguese/news/como-usar-variaveis-de-ambiente-do-node-com-um-arquivo-dotenv-para-node-js-e-npm/#:~:text=Como%20criar%20vari%C3%A1veis%20de%20ambiente,uma%20vari%C3%A1vel%20ao%20objeto%20process

**Comment by paulogesualdo** [comment]
Instruções adicionais: 
- [x] Instalar dotenv
- [x] Criar arquivo .env na raiz do projeto contendo as variáveis PORT, HOST, NODE_ENV
- [x] Criar pasta config na raiz do projeto

Dentro da pasta config:
- [x] Criar arquivo environmentVariables.js importando ('dotenv').config() e exportando as variáveis. Conferir pois eu havia escrito errado, é necessário () para executar a função config que está dentro de dotenv.
- [x] Criar arquivo index.js importando o arquivo environmentVariables e exportando como objeto

No index.js que está na raiz do projeto:
- [x] Importar a pasta config
- [x] Na linha que informa que o servidor foi iniciado, mostrar no console qual é a porta através de algo semelhante a `${config.environmentVariables.PORT}` e informar também o ambiente através de algo semelhante a `${config.environmentVariables.NODE_ENV}`

**Comment by magdieline** [comment]
feito conforme orientação. Sem duvidas
