### ISSUE TITLE
Configurar padrão de codigo

### ISSUE THREAD

**Issue by paulogesualdo** [magdieline/encurtador-de-url#8]
Segue link para auxiliar:

Video
https://www.youtube.com/watch?v=i26sZrPj2zY&ab_channel=MaykBrito

Material importante
https://medium.com/cwi-software/eslint-prettier-a-dupla-perfeita-para-produtividade-e-padroniza%C3%A7%C3%A3o-de-c%C3%B3digo-6a7730cfa358

**Comment by paulogesualdo** [comment]
Instruções adicionais:
- [x] Não instalar o eslint como dependência de produção, mas sim dependência de desenvolvimento (pois serve somente para o desenvolvimento, se for para a produção não vai servir para nada, só ocupará espaço)
- [x] À partir de agora, antes de instalar qualquer dependência, pensar se ela será de produção ou de desenvolvimento
- [x] Criar na raiz do projeto um arquivo chamado .eslintrc.js e colocar o conteúdo que está no meu GitHub Gists
- [x] Criar na raiz no projeto um arquivo chamado .eslintignore e adicionar a pasta node_modules
- [x] Instalar a extensão ESLint no VS Code
- [x] Ler novamente os tipos de commits e avaliar qual é o tipo correto para esta issue

**Comment by magdieline** [comment]
finalizado
